# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['backend/server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('database/schema.sql',                          'database'),
        ('database/migration_001_required_tests_and_runs.sql', 'database'),
        ('database/migration_002_sources_and_codes.sql', 'database'),
        ('database/migration_003_flakiness_weight_m0.sql','database'),
        ('database/migration_004_mb_moisture.sql',       'database'),
        ('database/migration_005_products_and_sieves.sql','database'),
        ('database/migration_006_specifications.sql',    'database'),
        ('database/migration_007_test_limits.sql',       'database'),
        ('database/migration_008_pdf_font.sql',          'database'),
        ('database/migration_009_ce_periods.sql',        'database'),
        ('database/migration_010_document_library.sql',  'database'),
        ('database/migration_011_pdf_font_ibmplex.sql',  'database'),
        ('standards.json',                               '.'),
        ('fonts',                                        'fonts'),
    ],
    hiddenimports=[
        'reportlab',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.colors',
        'reportlab.lib.units',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'reportlab.platypus',
        'reportlab.platypus.flowables',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.tables',
        'reportlab.graphics',
        'reportlab.graphics.shapes',
        'reportlab.graphics.charts',
        'reportlab.graphics.charts.barcharts',
        'reportlab.graphics.charts.linecharts',
        'reportlab.graphics.charts.lineplots',
        'reportlab.graphics.charts.piecharts',
        'reportlab.graphics.renderPDF',
        'sqlite3',
        'PIL',
        'PIL.Image',
        'charset_normalizer',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='lab-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='lab-backend',
)
